stages:
    - build
    - prepare
    - deploy

build:application:
    stage: build
    only:
        - master
    tags:
        - docker
    image: node:$NODE_VERSION-alpine
    script:
        - echo $RRREMOTE_FIREBASE_CREDS > fbc.json
        - npm install
        - npm run build
    artifacts:
        paths:
            - build/
            - fbc.json
        expire_in: 20 minutes

prepare:dockerimage:
    stage: prepare
    only:
        - master
    tags:
        - docker
    services:
        - docker:dind
    image: docker:stable
    dependencies:
        - build:application
    before_script:
        - docker info
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    script:
        - docker build -t $CI_REGISTRY_IMAGE .
        - docker push $CI_REGISTRY_IMAGE

deploy:graphqlgateway:
    stage: deploy
    tags:
        - internal-shell
    before_script:
        - docker info
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    script:
        - cd /home/rrremote
        - docker-compose pull graphqlgateway
        - docker-compose up -d --no-deps graphqlgateway